Feature/tines refactoring 1
sushiswap/sushiswap pull request #1248
Opened 2023-11-12 12:17 UTC by Okavango

2023-11-18 17:07 UTC, OlaStenberg approved these changes

2023-11-18 17:19 UTC, LufyCZ requested changes
I'd make the `uniqueId` function a getter instead. It can then be accessed with `pool.uniqueId` instead of `pool.uniqueId()`.

Doesn't matter functionally, just think it'd be nicer, your call.

[ref](https://stackoverflow.com/questions/12827266/get-and-set-in-typescript)

2023-11-18 18:32 UTC, Okavango commented
> I'd make the `uniqueId` function a getter instead. It can then be accessed with `pool.uniqueId` instead of `pool.uniqueId()`.
> 
> Doesn't matter functionally, just think it'd be nicer, your call.
> 
> [ref](https://stackoverflow.com/questions/12827266/get-and-set-in-typescript)

Good idea, but I would like to leave it as a function to remember that it makes something - not just a field

2023-11-18 18:37 UTC, merged

2023-11-19 11:01 UTC, LufyCZ commented
> > I'd make the `uniqueId` function a getter instead. It can then be accessed with `pool.uniqueId` instead of `pool.uniqueId()`.
> > Doesn't matter functionally, just think it'd be nicer, your call.
> > [ref](https://stackoverflow.com/questions/12827266/get-and-set-in-typescript)
> 
> Good idea, but I would like to leave it as a function to remember that it makes something - not just a field

If I understand it correctly, getters are "supposed" to be doing thing (/ making things). If they were just straight up returning something, it could theoretically just be a public variable, no need for a getter / function in that case.