feat: aptos data api update
sushiswap/sushiswap pull request #1669
Opened 2024-09-04 20:20 UTC by 0xMasayoshi

2024-09-11 19:24 UTC, matthewlilley commented on apps/web/src/app/(non-evm)/aptos/(positions)/providers.tsx
> +  const queryClient = new QueryClient()
Might cause hydration errors without:

const queryClient = useState(() => new QueryClient())

2024-09-12 15:48 UTC, LufyCZ requested changes

2024-09-12 15:48 UTC, LufyCZ commented on apps/web/src/app/(non-evm)/aptos/(common)/lib/common/use-token-balances.ts
> +  const aptos = new Aptos(
might make sense to extract this for reusability?

2024-09-12 15:48 UTC, LufyCZ commented on apps/web/src/app/(non-evm)/aptos/explore/layout.tsx
> +          <Providers>{children}</Providers>
there's already a QueryClientProvider in the level above

2024-09-12 15:48 UTC, LufyCZ commented on apps/web/src/app/(non-evm)/aptos/pool/[address]/page.tsx
> +            <PoolComposition row={pool} />
might be nice to have loading states for these things but would be a lot of work for not a lot of gain (#TODO #FixSomeday)

2024-09-12 15:48 UTC, LufyCZ commented on apps/web/src/app/(non-evm)/aptos/pool/lib/use-top-pools.ts
> +    staleTime: Infinity,
will `getTopNonEvmPools` ever change? if staleTime is set to Infinity...

2024-09-12 15:48 UTC, LufyCZ commented on apps/web/src/app/(non-evm)/aptos/explore/layout.tsx
> +          <Providers>{children}</Providers>
ah guess you fixed it and I didn't have the changes locally

2024-09-12 19:43 UTC, merged